### ISSUE TITLE
Failed to build on: Apple clang version 15.0.0 (clang-1500.1.0.2.5), NTL 11.5.1; easy patch

### ISSUE THREAD

**Issue by Artoria2e5** [vigna/CPRNG#1]
I'm trying to run `mspec` on the infamous RANDU number for fun and kicks, but it's just not cooperating. All of the commands in comp.sh throw the same error, so I will just post one:

```sh
g++ -std=c++17 -O3 -march=native spect.cpp -o spect -lntl
```

Here g++ is an alias to clang++. Anyways, it does the following:
[out.txt](https://github.com/vigna/CPRNG/files/14468497/out.txt)

`g++ --version` gives:
```
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

* * *

Reading the error shows that there's some indecision between `uint64_t` and `unsigned long`. While on x64 mac both `long` and `long long` are 64 bits, the typedef goes to `unsigned long long`. Because NTL only gives conv in `unsigned long`, the compiler just won't take it.

I, uh, just threw `unsigned long` explicitly into the template arguments in `common.cpp`. Then it just worked:
```C++
template <> ZZ NTL_NAMESPACE::conv<>(const uint128_t& x) {
	return conv<ZZ, unsigned long>(uint64_t(x >> 64)) << 64 | conv<ZZ, unsigned long>((uint64_t&)x);
}

template <> uint128_t NTL_NAMESPACE::conv<>(const ZZ& x) {
	return uint128_t(conv<unsigned long>(x >> 64 & conv<ZZ>(0xFFFFFFFFFFFFFFFF))) << 64 | conv<unsigned long>(x & conv<ZZ>(0xFFFFFFFFFFFFFFFF));
}

template <> string hex<>(uint64_t a) {
	return hex(conv<ZZ, unsigned long>(a));
}
```

Now I'm happy. I don't know, should I complain to the guys at NTL?

* * *
Alright, there is one more issue in `search.cpp`, line 149. Again, specify the type as:
```C++
			a = ((((conv<ZZ>(0) + next()) << 192) + ((conv<ZZ>(0) + next()) << 128) + ((conv<ZZ>(0) + next()) << 64) + conv<ZZ, unsigned long>(next())) & multiplier_mask) | multiplier_surround_bits;
```
and it works.

**Comment by vigna** [comment]
Yes, definitelym reporting to NTL is the right thing to do. `uint64_t` is a standard C99 type—people shouldn't fight against the number of `long` in the type definition.

I have a Mac but I use GCC so probably I never stumbled into this. Thanks for reporting. I added some conditional compilation and that should circumvent the problem for now.
